run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple

linters-settings:
  errcheck:
    check-blank: false

issues:
  exclude-dirs:
    - frontend
    - build
  exclude-files:
    - "^main\\.go$"
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
