// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {extractor} from '../models';
import {app} from '../models';
import {config} from '../models';

export function Activate(arg1:string):Promise<boolean>;

export function CancelExtraction():Promise<void>;

export function ExportData(arg1:Array<extractor.Record>,arg2:string):Promise<app.ExtractResult>;

export function ExtractToPath(arg1:string,arg2:string,arg3:Array<string>):Promise<app.ExtractResult>;

export function GetMachineID():Promise<string>;

export function GetTrialStatus():Promise<config.TrialStatus>;

export function OpenFile(arg1:string):Promise<void>;

export function PreviewData(arg1:string,arg2:Array<string>):Promise<app.ExtractResult>;

export function ScanFields(arg1:string):Promise<Array<app.FieldOption>>;

export function SelectFile():Promise<string>;

export function SelectOutputPath(arg1:string):Promise<string>;
