// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Activate(arg1) {
  return window['go']['app']['App']['Activate'](arg1);
}

export function CancelExtraction() {
  return window['go']['app']['App']['CancelExtraction']();
}

export function ExportData(arg1, arg2) {
  return window['go']['app']['App']['ExportData'](arg1, arg2);
}

export function ExtractToPath(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExtractToPath'](arg1, arg2, arg3);
}

export function GetMachineID() {
  return window['go']['app']['App']['GetMachineID']();
}

export function GetTrialStatus() {
  return window['go']['app']['App']['GetTrialStatus']();
}

export function OpenFile(arg1) {
  return window['go']['app']['App']['OpenFile'](arg1);
}

export function PreviewData(arg1, arg2) {
  return window['go']['app']['App']['PreviewData'](arg1, arg2);
}

export function ScanFields(arg1) {
  return window['go']['app']['App']['ScanFields'](arg1);
}

export function SelectFile() {
  return window['go']['app']['App']['SelectFile']();
}

export function SelectOutputPath(arg1) {
  return window['go']['app']['App']['SelectOutputPath'](arg1);
}
